### PR TITLE
Add SailfishOS:Chum metadata for display in the Chum GUI app

### PR DESCRIPTION
**Pull request by poetaster**
Again, the question if we wish to have screenshots.
I believe we might want to turn on discussions? Turn off Projects?

### CODE REVIEW

**Comment by Olf0** [comment]
> Again, the question if we wish to have screenshots.

???
You can have screenshots any time!
More seriously: I do not comprehend, what you intend to address with "[Do] we wish to have screenshots?".

> I believe we might want to turn on discussions?

I don't think so, because issues turned out to be superior in every aspect I tried and can think of.  The crucial point is that "convert into issue" does not work / is a bad joke: It copies the discussion title and discards all messages!

> Turn off Projects?

Ack, missed that: Done.

WRT the commit proper:
* Thanks!
* Please adhere to https://github.com/storeman-developers/harbour-storeman/wiki/Git-commit-workflow
  I.e., default branch to pose PRs to is `devel`.  I adapted this PR accordingly.
* Linguistic nitpicking: Don't ask my why the conventions are for commit and PR descriptions to use present tense and never use a full stop for the title (even when it is a full sentence!?!).  I adapted this PR accordingly.
* I will look at the details in the upcoming days and see if I may add something.

**Comment by Olf0** [comment]
Please set the default branch in your repo settings at GitHub's web-frontent to the `devel` branch.
Because you started at the `master` branch this results in shoving two old commits in a circle, which is something git does not like at all.  Rebasing would be a way out, but I just copy & paste these few lines into a new PR.

Hence closing.

**Comment by poetaster** [comment]
Hmmm. Doesn't even show devel in my fork? And dev is stale. Maybe it would be easier to simply work directly on branches in this repository?

**Comment by poetaster** [comment]
> Ah, screenshots to be displayed in the SailfishOS:Chum GUI application.

I've made a ticket but can't seem to assign myself to deal with it? Normally, I would pull these tasks out, make a ticket and assign myself.
https://github.com/storeman-developers/harbour-storeman/issues/225

**Comment by poetaster** [comment]
I think for the sake of simplicity it would really make sense to have a poetaster-devel branch here. then I can reference that branch for issues (once I can assign them to self) and one doesn't jumpg about.

I'm guessing, but I wold guess that I have to drop my current fork and fork again to pick up the structural changes you made here. Or some kind of rebase?

**Comment by Olf0** [comment]
> Hmmm. Doesn't even show devel in my fork? And dev is stale.

Oh, your fork is stale!  You never seem to have synchronised it with upstream!?!

Before you start to commit anything you must update your fork.  Either at the command line or by clicking on GitHub_Fetch-Upstream






> I think for the sake of simplicity it would really make sense to have a poetaster-devel branch here. then I can reference that branch for issues (once I can assign them to self) and one doesn't jumpg about.
> 
> I'm guessing, but I wold guess that I have to drop my current fork and fork again to pick up the structural changes you made here. Or some kind of rebase?

See above.

**Comment by Olf0** [comment]
> I've made a ticket but can't seem to assign myself to deal with it? Normally, I would pull these tasks out, make a ticket and assign myself.

Oh, I missed out some configuration steps WRT you for both repos.  Done now.

BTW, issue assignment is IMO just a publicly visible flag or are you aware of any function it has
besides being able to list all issues assigned to <somebody>?

Can you please support me with handling future incoming issues and PRs from others.  Up to now, I have been handling these alone.

> #225

Is obsolete since yesterday.

**Comment by poetaster** [comment]
I think for the sake of simplicity it would really make sense to have a poetaster-devel branch here. then I can reference that branch for issues (once I can assign them to self) and one doesn't jumpg about.

I'm guessing, but I wold guess that I have to drop my current fork and fork again to pick up the structural changes you made here. Or some kind of rebase?

> > Hmmm. Doesn't even show devel in my fork? And dev is stale.
> 
> Oh, your fork is stale! You never seem to have synchronised it with upstream!?! If this is the case is always shown to the left of the ellipse marked in the screenshot below.
> 
> Before you start to commit anything you always should update your fork. Either at the command line or by clicking on GitHub_Fetch-Upstream
> 
> > I think for the sake of simplicity it would really make sense to have a poetaster-devel branch here. then I can reference that branch for issues (once I can assign them to self) and one doesn't jumpg about.
> > I'm guessing, but I wold guess that I have to drop my current fork and fork again to pick up the structural changes you made here. Or some kind of rebase?
> 
> See above.



> Oh, your fork is stale! You never seem to have synchronised it with upstream!?!

That is not relevant, and I did try fetching upstream. That did not lead to devel appearing. I think I need to fork again.

**Comment by poetaster** [comment]
> BTW, issue assignment is IMO just a publicly visible flag or are you aware of any function it has
> besides being able to list all issues assigned to ?

It's useful for ME to see what I have agreed to do and should be paying attention to.

**Comment by Olf0** [comment]
> > BTW, issue assignment is IMO just a publicly visible flag or are you aware of any function it has besides being able to list all issues assigned to ?
> 
> It's useful for ME to see what I have agreed to do and should be paying attention to. It's useful to you if I've assigned myself you can safely ignore it.

https://github.com/storeman-developers/harbour-storeman/issues/226#issuecomment-1069437309

**Comment by Olf0** [comment]
> That is not relevant, and I did try fetching upstream. That did not lead to devel appearing. I think I need to fork again.

https://github.com/storeman-developers/harbour-storeman/issues/226#issuecomment-1069437309

**Pull request closed without merging**
