### PR TITLE
App icon refresh

### PR DESCRIPTION
**Pull request by JSEHV**
App icon refresh

### CODE REVIEW

**Comment by mentaljam** [comment]
Launched a [vote](https://docs.google.com/forms/d/e/1FAIpQLSe19eSonDfndTJ8eCGx4RFNf5WGw_3rT7gFvi72Ye_yf0VnlA/viewform) for accepting this PR

**Comment by Olf0** [comment]
@JSEHV, I like the new icon a lot, but IMO the SailfishOS logo should bigger to become better visible / recognisable.
It also looks / appears / is a bit off centre, like being shifted to the lower left corner of the package.

TL;DR: The SailfishOS logo scaled to 110% to 120% of its current size and moved a bit to the upper right corner of the side it is "printed" on might look better.

Other ideas:
* Increase the size of the white label.
* Put something on the white label, e.g. **SFOS** or **Storeman**
* Rotate the package a bit to the right (i.e., anti-clockwise), so it is not displayed in an exactly symmetrical position, in order to create a more 3D look.  That would also expose the side with SailfishOS logo better.

**Comment by mentaljam** [comment]
@JSEHV, thanks for the icon. I'll merge the PR, but I want to see your opinion on some points:

- About increasing the contrast as @direc85 [suggested](https://forum.sailfishos.org/t/poll-storeman-icon-2/7187/6?u=mentaljam)
- About @Olf0's suggestions
- About the current cover background [image](https://github.com/mentaljam/harbour-storeman/blob/0e4cbc1097dcd152594d760260d52689f07b80c1/qml/cover/background.svg) which is made from the old icon

Also I ask you to remove all the PNG files from the PR and leave only SVG

**Comment by Olf0** [comment]
Closing this PR, because there was no reaction from the original author of this PR for more than a year.

Furthermore the requirements have changed: Now the SVG plus an export in certain PNG sizes are needed, but more sizes than before.

I also took the time to analyse a couple of aspects of the current icon by laurent_c, such as perspective, shading, shadows etc., which let me comprehend that the draft of this new icon is not up to the standards of the current one.

This PR can be reopened at any time, if a reworked version of the new icon is submitted.  I suggest to submit an SVG first, so its style and properties can be discussed and only export the PNGs when we have agreed on an SVG version as final.

**Pull request closed without merging**
