### PR TITLE
Packaging fixes

### PR DESCRIPTION
**Pull request by Thaodan**

### CODE REVIEW

**Comment by Olf0** [comment]
Thank you, this all makes sense, but does not resolve issue #160!

I still have to check, what the switch from the `%setup` to the `%autosetup` macro provides.  I do concur with all other changes.

**Comment by Olf0** [comment]
Thank you for the explanations in the commit messages.  But why "[- %autosetup should be used instead of %setup where possible](https://github.com/storeman-developers/harbour-storeman/pull/302/commits/2326af0a2b5552894a298396c3f5acf111822799)"?

AFAIU it [only provides the additional ability to apply simple patches](https://pagure.io/packaging-committee/issue/388#comment-144236) over `%setup`, which never will be necessary for a project which is "upstream" and has no "downstream" packagers.

**Comment by Thaodan** [comment]
> AFAIU `%autosetup` [only provides the additional ability to apply simple patches](https://pagure.io/packaging-committee/issue/388#comment-144236) over `%setup`, which never will be necessary for a project which is "upstream" and has no "downstream" packagers.

It is just cleaner, there's just no real reason to use %setup these days.

**Comment by Thaodan** [comment]
>@Olf0
>[Merge branch 'devel' into libsolv_pkgconfig](https://github.com/storeman-developers/harbour-storeman/pull/302/commits/3b6d97c1fd0bb197101753d5e188c96a3470d893)

You can use git rebase instead of a cleaner git history.

**Comment by Olf0** [comment]
> You can use git rebase instead of a cleaner git history.

Thank you for the hint and I understand that this would have omitted a superfluous merge in the history.
Still I use processes with GitHub's web-frontend, which I know well and fully understand, because I do not have sufficient time to learn Git and I never wanted to maintain Storeman* alone, but everybody else bailed out.

Please take a look at the last open and original question in issue #160 and https://github.com/storeman-developers/harbour-storeman/pull/302#issuecomment-1126217962
Thanks!

**Pull request merged**
